name = "glossy-llm-proxy"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
FIREBASE_PROJECT_ID = "glossy-2259d"
FIREBASE_API_KEY = "AIzaSyC_-isd9XtyX6uV8kv4YdbWIEmaHTs0qZU"
